image: gitpod/workspace-python

tasks:
  - name: Install java
    command: |
      curl -s "https://get.sdkman.io" | bash
      source "$HOME/.sdkman/bin/sdkman-init.sh"
      sdk install java 17.0.11-tem
      sdk use java 17.0.11-tem
  - name: Install graphiz
    command: |
      apt-get update
      apt-get install -y graphviz
  - name: Install deps and enter shell
    command: |
      poetry config virtualenvs.in-project true
      poetry install
      poetry shell

checkoutLocation: "."
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
